/**
 * The JSON contract, typed.
 *
 * Python owns the data, this app owns the presentation, and they meet ONLY here.
 *
 * Runtime validation lives in `schemas.ts` and runs in development only — see `loadJson`.
 */
import type {
  Build,
  CandidateRow,
  Company,
  CompanyIndexRow,
  EventRow,
  QuestionRow,
  Rfp,
  RunRow,
  SourceRow,
  Stats,
} from "./schemas";

export type {
  Build,
  CandidateRow,
  Company,
  CompanyIndexRow,
  EventRow,
  QuestionRow,
  Rfp,
  RunRow,
  SourceRow,
  Stats,
};

/* ------------------------------------------------------------------ loading */

const BASE = `${import.meta.env.BASE_URL}data`;

async function loadJson<T>(path: string): Promise<T> {
  const res = await fetch(`${BASE}/${path}`);
  if (!res.ok) {
    throw new Error(
      `Could not load ${path} (HTTP ${res.status}). The data layer has not been generated — run \`python tools/site_data.py\`.`,
    );
  }
  const raw = await res.json();

  // Development only. The data is generated by `tools/site_data.py`, whose suite already asserts
  // the shape and determinism of every file — so in production the guarantee holds before the
  // browser is involved. In development shapes genuinely DO drift: this caught two real contract
  // mismatches on the day it was written. The dynamic import keeps Zod out of the production graph
  // entirely rather than merely hoping it is shaken out.
  if (import.meta.env.DEV) {
    const { validate } = await import("./schemas");
    validate(path, raw);
  }
  return raw as T;
}

/** Cached once per page load — the data is static for the life of the build. */
function once<T>(fn: () => Promise<T>): () => Promise<T> {
  let p: Promise<T> | undefined;
  return () => {
    p ??= fn();
    return p;
  };
}

export const getIndex = once(() => loadJson<CompanyIndexRow[]>("index.json"));
export const getStats = once(() => loadJson<Stats>("stats.json"));
export const getSources = once(() => loadJson<SourceRow[]>("sources.json"));
export const getRuns = once(() => loadJson<RunRow[]>("runs.json"));
export const getEvents = once(() => loadJson<EventRow[]>("events.json"));
export const getRfps = once(() => loadJson<Rfp[]>("rfps.json"));
export const getQuestions = once(() => loadJson<QuestionRow[]>("questions.json"));
export const getBuild = once(() => loadJson<Build>("build.json"));
export const getCandidates = once(() => loadJson<CandidateRow[]>("candidates.json"));

export function getCompany(slug: string): Promise<Company> {
  return loadJson<Company>(`companies/${slug}.json`);
}
